"""empty message

Revision ID: 9a37f149659e
Revises: b29f572419b9
Create Date: 2022-09-18 13:29:17.685686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a37f149659e'
down_revision = 'b29f572419b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'favorites', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
