"""empty message

Revision ID: e1f80750d533
Revises: d4e3018ab04e
Create Date: 2022-09-19 21:14:19.778776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f80750d533'
down_revision = 'd4e3018ab04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favorite_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'user', ['favorite_id'], ['id'])
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'favorites', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_id')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'favorite_id')
    # ### end Alembic commands ###
